
INSERT INTO manager."user" (id, role_id, username, email, password, status) VALUES (default, 1, 'daniil', 'na', '123', 'A');
INSERT INTO manager."user" (id, role_id, username, email, password, status) VALUES (default, 2, 'kevin', 'na', '123', 'A');
INSERT INTO manager."user" (id, role_id, username, email, password, status) VALUES (default, 2, 'uve', 'na', '123', 'A');

INSERT INTO manager.role (id, name) VALUES (default, 'Guest');
INSERT INTO manager.role (id, name) VALUES (default, 'Scout');
INSERT INTO manager.role (id, name) VALUES (default, 'Admin');
INSERT INTO manager.role (id, name) VALUES (default, 'Coach');

INSERT INTO manager.confederation (id, name, description) VALUES (default, 'UEFA', 'Union of European Football Associations');
INSERT INTO manager.confederation (id, name, description) VALUES (default, 'CONCACAF', 'Confederation of North, Central American and Caribbean Association Football');
INSERT INTO manager.confederation (id, name, description) VALUES (default, 'CONMEBOL', 'Confederación Sudamericana de Fútbol');
INSERT INTO manager.confederation (id, name, description) VALUES (default, 'CAF', 'Confederation of African Football');
INSERT INTO manager.confederation (id, name, description) VALUES (default, 'AFC', 'Asian Football Confederation');
INSERT INTO manager.confederation (id, name, description) VALUES (default, 'OFC', 'Oceania Football Confederation');

INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Albania');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Andorra');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Armenia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Austria');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Azerbaijan');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Belarus');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Belgium');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Bosnia and Herzegovina');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Bulgaria');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Croatia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Cyprus');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Czech Republic');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Denmark');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'England');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Estonia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Faroe Islands');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Finland');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'France');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Georgia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Germany');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Gibraltar');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Greece');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Hungary');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Iceland');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Republic of Ireland');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Israel');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Italy');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Kazakhstan');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Kosovo');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Latvia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Liechtenstein');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Lithuania');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Luxembourg');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Malta');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Moldova');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Montenegro');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Netherlands');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'North Macedonia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Northern Ireland');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Norway');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Poland');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Portugal');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Romania');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Russia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'San Marino');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Scotland');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Serbia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Slovakia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Slovenia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Spain');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Sweden');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Switzerland');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Turkey');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Ukraine');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Wales');

INSERT INTO manager.league (id, country_id, name) VALUES (default, 16, 'Meistriliiga');
INSERT INTO manager.league (id, country_id, name) VALUES (default, 16, 'Esiliiga');
INSERT INTO manager.league (id, country_id, name) VALUES (default, 16, 'Esiliiga B');
INSERT INTO manager.league (id, country_id, name) VALUES (default, 16, 'II liiga');
INSERT INTO manager.league (id, country_id, name) VALUES (default, 16, 'III liiga');
INSERT INTO manager.league (id, country_id, name) VALUES (default, 16, 'IV liiga');

INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 1, 31, 'Tallinna FC Flora');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 1, 31, 'FCI Tallinn');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 1, 31, 'Tallinna FC Levadia');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 1, 19, 'JK Narva Trans');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 1, 31, 'Nõmme Kalju FC');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 1, 22, 'Paide Linnameeskond');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 1, 23, 'Pärnu JK Vaprus');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 1, 29, 'JK Sillamäe Kalev');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 1, 32, 'Tartu JK Tammeka');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 1, 41, 'Viljandi JK Tulevik');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 2, 24, 'Rakvere JK Tarvas');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 2, 16, 'Maardu Linnameeskond');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 2, 32, 'Tartu FC Santos');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 2, 31, 'JK Tallinna Kalev');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 2, 31, 'FCI Tallinn U21');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 2, 31, 'Tallinna FC Levadia U21');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 2, 31, 'Tallinna FC Flora U21');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 2, 1, 'FC Elva');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 2, 11, 'FC Kuressaare');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 2, 32, 'Tartu JK Welco');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 3, 40, 'JK Vändra Vaprus');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 3, 31, 'Nõmme Kalju FC U21');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 3, 22, 'Paide Linnameeskond U21');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 3, 9, 'Kohtla-Järve JK Järve');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 3, 25, 'Raasiku FC Joker');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 3, 32, 'Tartu JK Tammeka U21');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 3, 2, 'Viimsi JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 3, 29, 'JK Sillamäe Kalev U21');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 3, 31, 'JK Tallinna Kalev U21');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 3, 7, 'Keila JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 31, 'Tallinna JK Legion');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 43, 'Võru FC Helios');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 5, 'Jõgeva SK Noorus-96');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 32, 'Tartu FC Merkuur');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 31, 'Lasnamäe FC Ajax');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 31, 'Tallinna FC Levadia III');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 19, 'Narva United');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 31, 'Tallinna JK Piraaja');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 31, 'Tallinna JK Dünamo');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 16, 'Maardu Linnameeskond II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 32, 'Tartu FC Santos II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 16, 'Maardu United');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 31, 'FC Ararat Tallinn');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 9, 'Kohtla-Järve JK Järve II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 31, 'FC Nõmme United');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 23, 'Pärnu JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 27, 'Saue JK Laagri');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 41, 'Viljandi JK Tulevik U21');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 31, 'JK Tabasalu');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 34, 'JK Ganvix Türi');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 26, 'Raplamaa JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 31, 'Tallinna FC Flora U19');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 20, 'FC Otepää');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 11, 'FC Kuressaare II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 35, 'Tõrva JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 23, 'Pärnu JK Vaprus II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 33, 'SK Imavere');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, 2, 'Viimsi JK II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'Põhja-Tallinna JK Volta');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'Tallinna FC Hell Hunt');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'JK Tallinna Kalev III');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'JK Retro');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'Tallinna FC Eston Villa');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'Rumori Calcio Tallinn');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'Pirita Reliikvia');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 27, 'Harju JK Laagri');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 28, 'Saku Sporting');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'Nõmme Kalju FC III');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'Kristiine JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'Tallinna KSK FC Štrommi');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 32, 'Tartu JK Welco II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 33, 'FC Tarvastu');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 37, 'FC Vastseliina');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 35, 'SK Tääksi');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 36, 'FC Tartu');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 32, 'Tartu JK Tammeka U19');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 41, 'Viljandi JK Tulevik III');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 5, 'FC Jõgeva Wolves');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 30, 'Suure-Jaani United');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 36, 'EMÜ SK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 32, 'Tartu Ülikool Fauna');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 39, 'Navi Vutiselts');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 22, 'Paide Linnameeskond III');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'FCI Tallinn III');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 42, 'JK Väätsa Vald');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 5, 'FC Järva-Jaani');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 25, 'Raasiku FC Joker II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 34, 'Koeru JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 15, 'Ambla Vallameeskond');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 15, 'JK Loo');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 43, 'Kuusalu JK Rada');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 32, 'FC Helios Tartu');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'Lasnamäe FC Ajax II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'Tallinna JK Augur');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 23, 'Pärnu JK Poseidon');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'Tallinna FC Castovanni Eagles');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 14, 'Lihula JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 18, 'Kärdla Linnameeskond');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 21, 'Läänemaa JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'FC Zenit Tallinn');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 38, 'Rummu Dünamo');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 33, 'FC Kose');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'JK Kernu Kadakas');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 13, 'FC Lelle');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 26, 'Raplamaa JK II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 21, 'Pakri SK Alexela');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'Tallinna FC Zapoos');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 15, 'Tallinna Depoo');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'Tallinna FC Olympic Olybet');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 3, 'Anija JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'Tallinna JK Piraaja II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 16, 'FC Maardu Aliens');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 24, 'Rakvere JK Tarvas II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'Tallinna JK Jalgpallihaigla');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 3, 'Haapsalu JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 10, 'Kohila Püsivus');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'Tallinna FC Soccernet');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 9, 'Maarjamäe FC Igiliikur');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 9, 'Tallinna FC Transferwise');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 9, 'FC Toompea');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 7, 'Keila JK II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 31, 'Põhja-Tallinna JK Volta II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 9, 'Tallinna FC Reaal');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 9, 'Tallinna Majandusmagistri Jalgpalliselts');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 36, 'Valga FC Warrior');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 39, 'Võru FC Helios II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 23, 'Pärnu JK Poseidon II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 1, 'FC Elva II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 36, 'Põlva FC Lootos');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 23, 'FCP Pärnu');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 5, 'FC Jõgeva Wolves II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 41, 'Viljandi JK Tulevik IV');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, 35, 'Tõrva JK II');

INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 1, 'Lionel Messi', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 2, 'Cristiano Ronaldo', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 3, 'Robert Lewandowski', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 4, 'Kevin De Bruyne', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 5, 'Kylian Mbappe', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 6, 'Neymar Jr.', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 7, 'Mohamed Salah', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 8, 'Virgil van Dijk', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 9, 'Manuel Neuer', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 10, 'Luka Modric', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 11, 'Sergio Aguero', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 12, 'Luis Suarez', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 13, 'Erling Haaland', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 14, 'Gianluigi Donnarumma', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 15, 'Gareth Bale', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 16, 'Sergio Ramos', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 17, 'Harry Kane', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 18, 'Bruno Fernandes', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 19, 'Eden Hazard', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 20, 'Sadio Mane', 'A');

INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 1, 'M', 34, '1987-06-24', 170, 72, 'ARG', 'L');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 2, 'M', 37, '1985-02-05', 187, 83, 'POR', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 3, 'M', 33, '1988-08-21', 185, 81, 'POL', 'B');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 4, 'M', 30, '1991-06-28', 181, 70, 'BEL', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 5, 'M', 23, '1998-12-20', 178, 73, 'FRA', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 6, 'M', 30, '1992-02-05', 175, 68, 'BRA', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 7, 'M', 29, '1992-06-15', 175, 71, 'EGY', 'L');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 8, 'M', 21, '2000-07-21', 194, 88, 'NED', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 9, 'M', 34, '1987-12-19', 185, 81, 'GER', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 10, 'M', 31, '1990-06-24', 180, 68, 'CRO', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 11, 'M', 30, '1992-05-02', 168, 70, 'ARG', 'L');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 12, 'M', 33, '1988-03-24', 170, 75, 'URY', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 13, 'M', 26, '1995-03-20', 177, 73, 'NOR', 'L');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 14, 'M', 29, '1992-07-21', 173, 68, 'ITA', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 15, 'M', 32, '1989-06-11', 170, 72, 'WAL', 'L');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 16, 'M', 34, '1987-10-19', 169, 70, 'ESP', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 17, 'M', 25, '1996-02-11', 180, 77, 'ENG', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 18, 'M', 27, '1994-07-11', 174, 71, 'POR', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 19, 'M', 28, '1993-01-24', 185, 80, 'BEL', 'L');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 20, 'M', 29, '1992-04-15', 182, 78, 'SEN', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 1, 'M', 34, '1987-06-24', 170, 72, 'ARG', 'L');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 2, 'M', 37, '1985-02-05', 187, 83, 'POR', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 3, 'M', 33, '1988-08-21', 185, 81, 'POL', 'B');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 4, 'M', 30, '1991-06-28', 181, 70, 'BEL', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 5, 'M', 23, '1998-12-20', 178, 73, 'FRA', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 6, 'M', 30, '1992-02-05', 175, 68, 'BRA', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 7, 'M', 29, '1992-06-15', 175, 71, 'EGY', 'L');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 8, 'M', 21, '2000-07-21', 194, 88, 'NED', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 9, 'M', 34, '1987-12-19', 185, 81, 'GER', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 10, 'M', 31, '1990-06-24', 180, 68, 'CRO', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 11, 'M', 30, '1992-05-02', 168, 70, 'ARG', 'L');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 12, 'M', 33, '1988-03-24', 170, 75, 'URY', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 13, 'M', 26, '1995-03-20', 177, 73, 'NOR', 'L');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 14, 'M', 29, '1992-07-21', 173, 68, 'ITA', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 15, 'M', 32, '1989-06-11', 170, 72, 'WAL', 'L');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 16, 'M', 34, '1987-10-19', 169, 70, 'ESP', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 17, 'M', 25, '1996-02-11', 180, 77, 'ENG', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 18, 'M', 27, '1994-07-11', 174, 71, 'POR', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 19, 'M', 28, '1993-01-24', 185, 80, 'BEL', 'L');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 20, 'M', 29, '1992-04-15', 182, 78, 'SEN', 'R');
