
INSERT INTO manager.role (id, name) VALUES (default, 'guest');
INSERT INTO manager.role (id, name) VALUES (default, 'scout');
INSERT INTO manager.role (id, name) VALUES (default, 'admin');
INSERT INTO manager.role (id, name) VALUES (default, 'coach');

INSERT INTO manager.confederation (id, name, description) VALUES (default, 'UEFA', 'Union of European Football Associations');
INSERT INTO manager.confederation (id, name, description) VALUES (default, 'CONCACAF', 'Confederation of North, Central American and Caribbean Association Football');
INSERT INTO manager.confederation (id, name, description) VALUES (default, 'CONMEBOL', 'Confederación Sudamericana de Fútbol');
INSERT INTO manager.confederation (id, name, description) VALUES (default, 'CAF', 'Confederation of African Football');
INSERT INTO manager.confederation (id, name, description) VALUES (default, 'AFC', 'Asian Football Confederation');
INSERT INTO manager.confederation (id, name, description) VALUES (default, 'OFC', 'Oceania Football Confederation');

INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Albania');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Andorra');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Armenia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Austria');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Azerbaijan');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Belarus');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Belgium');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Bosnia and Herzegovina');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Bulgaria');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Croatia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Cyprus');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Czech Republic');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Denmark');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'England');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Estonia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Faroe Islands');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Finland');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'France');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Georgia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Germany');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Gibraltar');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Greece');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Hungary');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Iceland');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Republic of Ireland');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Israel');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Italy');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Kazakhstan');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Kosovo');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Latvia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Liechtenstein');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Lithuania');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Luxembourg');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Malta');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Moldova');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Montenegro');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Netherlands');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'North Macedonia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Northern Ireland');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Norway');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Poland');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Portugal');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Romania');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Russia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'San Marino');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Scotland');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Serbia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Slovakia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Slovenia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Spain');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Sweden');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Switzerland');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Turkey');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Ukraine');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 1, 'Wales');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 3, 'Argentina');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 3, 'Bolivia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 3, 'Brazil');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 3, 'Chile');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 3, 'Colombia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 3, 'Ecuador');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 3, 'Paraguay');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 3, 'Peru');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 3, 'Uruguay');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 3, 'Venezuela');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Australia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Brunei');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Cambodia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Indonesia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Laos');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Malaysia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Myanmar');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Philippines');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Singapore');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Thailand');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'East Timor');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Vietnam');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Afghanistan');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Islamic Republic of Iran');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Kyrgyz Republic');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Tajikistan');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Turkmenistan');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Uzbekistan');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'China');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Chinese Taipei');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'DPR Korea');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Guam');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Hong Kong, China');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Japan');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Korea Republic');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Macau');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Mongolia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Northern Mariana Islands');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Bangladesh');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Bhutan');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'India');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Maldives');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Nepal');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Pakistan');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Sri Lanka');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Bahrain');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Iraq');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Jordan');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Kuwait');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Lebanon');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Oman');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Palestine');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Qatar');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Saudi Arabia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Syria');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'United Arab Emirates');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 5, 'Yemen');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Canada');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Mexico');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'United States');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Belize');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Costa Rica');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'El Salvador');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Guatemala');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Honduras');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Nicaragua');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Panama');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Anguilla');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Antigua and Barbuda');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Aruba');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Bahamas');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Barbados');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Bermuda');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Bonaire');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'British Virgin Islands');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Cayman Islands');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Cuba');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Curaçao');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Dominica');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Dominican Republic');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'French Guiana');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Grenada');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Guadeloupe');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Guyana');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Haiti');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Jamaica');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Martinique');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Montserrat');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Puerto Rico');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Saint Kitts and Nevis');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Saint Lucia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Saint Martin');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Saint Vincent and the Grenadines');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Sint Maarten');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Suriname');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Trinidad and Tobago');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'Turks and Caicos Islands');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 2, 'U.S. Virgin Islands');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Algeria');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Egypt');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Libya');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Morocco');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Tunisia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Benin');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Burkina Faso');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Cape Verde');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Gambia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Ghana');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Guinea');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Guinea-Bissau');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Ivory Coast');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Liberia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Mali');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Mauritania');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Niger');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Nigeria');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Senegal');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Sierra Leone');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Togo');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Cameroon');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Central African Republic');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Chad');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Congo');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'DR Congo');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Equatorial Guinea');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Gabon');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'São Tomé and Príncipe');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Burundi');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Djibouti');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Eritrea');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Ethiopia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Kenya');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Rwanda');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Somalia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'South Sudan');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Sudan');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Tanzania');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Uganda');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Zanzibar');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Angola');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Botswana');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Comoros');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Eswatini');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Lesotho');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Madagascar');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Malawi');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Mauritius');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Mozambique');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Namibia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Seychelles');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'South Africa');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Zambia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 4, 'Zimbabwe');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 6, 'American Samoa');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 6, 'Cook Islands');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 6, 'Fiji');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 6, 'Kiribati');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 6, 'New Caledonia');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 6, 'New Zealand');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 6, 'Papua New Guinea');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 6, 'Samoa');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 6, 'Solomon Islands');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 6, 'Tahiti');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 6, 'Tonga');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 6, 'Tuvalu');
INSERT INTO manager.country (id, confederation_id, name) VALUES (default, 6, 'Vanuatu');

INSERT INTO manager.league (id, country_id, name) VALUES (default, 15, 'Meistriliiga');
INSERT INTO manager.league (id, country_id, name) VALUES (default, 15, 'Esiliiga');
INSERT INTO manager.league (id, country_id, name) VALUES (default, 15, 'Esiliiga B');
INSERT INTO manager.league (id, country_id, name) VALUES (default, 15, 'II liiga');
INSERT INTO manager.league (id, country_id, name) VALUES (default, 15, 'III liiga');
INSERT INTO manager.league (id, country_id, name) VALUES (default, 15, 'IV liiga');

INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 1, null, 'Tallinna FC Flora');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 1, null, 'FCI Tallinn');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 1, null, 'Tallinna FC Levadia');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 1, null, 'JK Narva Trans');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 1, null, 'Nõmme Kalju FC');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 1, null, 'Paide Linnameeskond');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 1, null, 'Pärnu JK Vaprus');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 1, null, 'JK Sillamäe Kalev');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 1, null, 'Tartu JK Tammeka');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 1, null, 'Viljandi JK Tulevik');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 2, null, 'Rakvere JK Tarvas');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 2, null, 'Maardu Linnameeskond');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 2, null, 'Tartu FC Santos');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 2, null, 'JK Tallinna Kalev');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 2, null, 'FCI Tallinn U21');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 2, null, 'Tallinna FC Levadia U21');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 2, null, 'Tallinna FC Flora U21');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 2, null, 'FC Elva');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 2, null, 'FC Kuressaare');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 2, null, 'Tartu JK Welco');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 3, null, 'JK Vändra Vaprus');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 3, null, 'Nõmme Kalju FC U21');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 3, null, 'Paide Linnameeskond U21');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 3, null, 'Kohtla-Järve JK Järve');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 3, null, 'Raasiku FC Joker');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 3, null, 'Tartu JK Tammeka U21');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 3, null, 'Viimsi JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 3, null, 'JK Sillamäe Kalev U21');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 3, null, 'JK Tallinna Kalev U21');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 3, null, 'Keila JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Tallinna JK Legion');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Võru FC Helios');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Jõgeva SK Noorus-96');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Tartu FC Merkuur');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Lasnamäe FC Ajax');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Tallinna FC Levadia III');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Narva United');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Tallinna JK Piraaja');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Tallinna JK Dünamo');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Maardu Linnameeskond II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Tartu FC Santos II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Maardu United');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'FC Ararat Tallinn');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Kohtla-Järve JK Järve II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'FC Nõmme United');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Pärnu JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Saue JK Laagri');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Viljandi JK Tulevik U21');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'JK Tabasalu');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'JK Ganvix Türi');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Raplamaa JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Tallinna FC Flora U19');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'FC Otepää');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'FC Kuressaare II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Tõrva JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Pärnu JK Vaprus II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'SK Imavere');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 4, null, 'Viimsi JK II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Põhja-Tallinna JK Volta');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Tallinna FC Hell Hunt');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'JK Tallinna Kalev III');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'JK Retro');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Tallinna FC Eston Villa');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Rumori Calcio Tallinn');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Pirita Reliikvia');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Harju JK Laagri');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Saku Sporting');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Nõmme Kalju FC III');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Kristiine JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Tallinna KSK FC Štrommi');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Tartu JK Welco II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'FC Tarvastu');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'FC Vastseliina');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'SK Tääksi');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'FC Tartu');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Tartu JK Tammeka U19');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Viljandi JK Tulevik III');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'FC Jõgeva Wolves');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Suure-Jaani United');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'EMÜ SK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Tartu Ülikool Fauna');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Navi Vutiselts');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Paide Linnameeskond III');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'FCI Tallinn III');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'JK Väätsa Vald');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'FC Järva-Jaani');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Raasiku FC Joker II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Koeru JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Ambla Vallameeskond');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'JK Loo');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Kuusalu JK Rada');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'FC Helios Tartu');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Lasnamäe FC Ajax II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Tallinna JK Augur');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Pärnu JK Poseidon');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Tallinna FC Castovanni Eagles');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Lihula JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Kärdla Linnameeskond');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Läänemaa JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'FC Zenit Tallinn');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Rummu Dünamo');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'FC Kose');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'JK Kernu Kadakas');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'FC Lelle');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Raplamaa JK II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Pakri SK Alexela');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Tallinna FC Zapoos');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Tallinna Depoo');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Tallinna FC Olympic Olybet');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Anija JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Tallinna JK Piraaja II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'FC Maardu Aliens');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Rakvere JK Tarvas II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Tallinna JK Jalgpallihaigla');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Haapsalu JK');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Kohila Püsivus');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Tallinna FC Soccernet');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Maarjamäe FC Igiliikur');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Tallinna FC Transferwise');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'FC Toompea');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Keila JK II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Põhja-Tallinna JK Volta II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Tallinna FC Reaal');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Tallinna Majandusmagistri Jalgpalliselts');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Valga FC Warrior');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Võru FC Helios II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Pärnu JK Poseidon II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'FC Elva II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Põlva FC Lootos');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'FCP Pärnu');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'FC Jõgeva Wolves II');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Viljandi JK Tulevik IV');
INSERT INTO manager.club (id, league_id, city_id, name) VALUES (default, 5, null, 'Tõrva JK II');

INSERT INTO manager.position (id, code) VALUES (default, 'GK');
INSERT INTO manager.position (id, code) VALUES (default, 'DEF1');
INSERT INTO manager.position (id, code) VALUES (default, 'DEF2');
INSERT INTO manager.position (id, code) VALUES (default, 'DEF3');
INSERT INTO manager.position (id, code) VALUES (default, 'MID1');
INSERT INTO manager.position (id, code) VALUES (default, 'MID2');
INSERT INTO manager.position (id, code) VALUES (default, 'MID3');
INSERT INTO manager.position (id, code) VALUES (default, 'MID4');
INSERT INTO manager.position (id, code) VALUES (default, 'ATT1');
INSERT INTO manager.position (id, code) VALUES (default, 'ATT2');
INSERT INTO manager.position (id, code) VALUES (default, 'ATT3');

INSERT INTO manager.role (id, name) VALUES (default, 'guest');
INSERT INTO manager.role (id, name) VALUES (default, 'scout');
INSERT INTO manager.role (id, name) VALUES (default, 'admin');
INSERT INTO manager.role (id, name) VALUES (default, 'coach');

INSERT INTO manager."user" (id, role_id, username, email, password, status) VALUES (default, 3, 'daniil', 'daniil@El.Capitan.ee', '123', 'A');
INSERT INTO manager."user" (id, role_id, username, email, password, status) VALUES (default, 2, 'kevin', 'kevin@kahe-meetrised-jalad.ee', '123', 'A');
INSERT INTO manager."user" (id, role_id, username, email, password, status) VALUES (default, 2, 'uve', 'uve@mail.ee', '123', 'A');

INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 1, 'Lionel Messi', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 2, 'Cristiano Ronaldo', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 3, 'Robert Lewandowski', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 4, 'Kevin De Bruyne', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 5, 'Kylian Mbappe', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 6, 'Neymar Jr.', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 7, 'Mohamed Salah', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 8, 'Virgil van Dijk', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 9, 'Manuel Neuer', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 10, 'Luka Modric', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 11, 'Sergio Aguero', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 12, 'Luis Suarez', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 13, 'Erling Haaland', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 14, 'Gianluigi Donnarumma', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 15, 'Gareth Bale', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 16, 'Sergio Ramos', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 17, 'Harry Kane', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 18, 'Bruno Fernandes', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 19, 'Eden Hazard', 'A');
INSERT INTO manager.player (id, club_id, name, status) VALUES (default, 20, 'Sadio Mane', 'A');

INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 1, 'M', 34, '1987-06-24', 170, 72, 'ARG', 'L');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 2, 'M', 37, '1985-02-05', 187, 83, 'POR', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 3, 'M', 33, '1988-08-21', 185, 81, 'POL', 'B');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 4, 'M', 30, '1991-06-28', 181, 70, 'BEL', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 5, 'M', 23, '1998-12-20', 178, 73, 'FRA', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 6, 'M', 30, '1992-02-05', 175, 68, 'BRA', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 7, 'M', 29, '1992-06-15', 175, 71, 'EGY', 'L');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 8, 'M', 21, '2000-07-21', 194, 88, 'NED', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 9, 'M', 34, '1987-12-19', 185, 81, 'GER', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 10, 'M', 31, '1990-06-24', 180, 68, 'CRO', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 11, 'M', 30, '1992-05-02', 168, 70, 'ARG', 'L');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 12, 'M', 33, '1988-03-24', 170, 75, 'URY', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 13, 'M', 26, '1995-03-20', 177, 73, 'NOR', 'L');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 14, 'M', 29, '1992-07-21', 173, 68, 'ITA', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 15, 'M', 32, '1989-06-11', 170, 72, 'WAL', 'L');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 16, 'M', 34, '1987-10-19', 169, 70, 'ESP', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 17, 'M', 25, '1996-02-11', 180, 77, 'ENG', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 18, 'M', 27, '1994-07-11', 174, 71, 'POR', 'R');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 19, 'M', 28, '1993-01-24', 185, 80, 'BEL', 'L');
INSERT INTO manager.player_details (id, player_id, gender, age, birth_date, height, weight, nationality, best_foot) VALUES (default, 20, 'M', 29, '1992-04-15', 182, 78, 'SEN', 'R');

INSERT INTO manager.game (id, home_club_id, away_club_id, date) VALUES (default, 1, 2, '2023-02-15');
INSERT INTO manager.game (id, home_club_id, away_club_id, date) VALUES (default, 2, 3, '2023-04-29');
INSERT INTO manager.game (id, home_club_id, away_club_id, date) VALUES (default, 2, 1, '2023-06-05');
INSERT INTO manager.game (id, home_club_id, away_club_id, date) VALUES (default, 12, 2, '2024-04-24');
INSERT INTO manager.game (id, home_club_id, away_club_id, date) VALUES (default, 3, 10, '2024-04-24');
INSERT INTO manager.game (id, home_club_id, away_club_id, date) VALUES (default, 9, 2, '2024-04-24');
INSERT INTO manager.game (id, home_club_id, away_club_id, date) VALUES (default, 3, 15, '2024-04-24');

INSERT INTO manager.next_game (id, player_id, game_id, date, status, time) VALUES (default, 1, 1, '2024-06-20', 'A', '14:21:00');
INSERT INTO manager.next_game (id, player_id, game_id, date, status, time) VALUES (default, 1, 1, '2024-07-05', 'A', '10:45:00');
INSERT INTO manager.next_game (id, player_id, game_id, date, status, time) VALUES (default, 1, 1, '2024-08-12', 'A', '16:59:00');
INSERT INTO manager.next_game (id, player_id, game_id, date, status, time) VALUES (default, 2, 2, '2024-05-25', 'A', '09:37:00');
INSERT INTO manager.next_game (id, player_id, game_id, date, status, time) VALUES (default, 2, 2, '2024-06-08', 'A', '11:52:00');
INSERT INTO manager.next_game (id, player_id, game_id, date, status, time) VALUES (default, 2, 2, '2024-07-30', 'A', '15:14:00');
INSERT INTO manager.next_game (id, player_id, game_id, date, status, time) VALUES (default, 3, 3, '2024-08-21', 'A', '12:27:00');
INSERT INTO manager.next_game (id, player_id, game_id, date, status, time) VALUES (default, 3, 3, '2024-06-17', 'A', '08:59:00');
INSERT INTO manager.next_game (id, player_id, game_id, date, status, time) VALUES (default, 3, 3, '2024-05-10', 'A', '13:42:00');
INSERT INTO manager.next_game (id, player_id, game_id, date, status, time) VALUES (default, 4, 4, '2024-06-28', 'A', '17:05:00');
INSERT INTO manager.next_game (id, player_id, game_id, date, status, time) VALUES (default, 4, 4, '2024-07-15', 'A', '09:23:00');
INSERT INTO manager.next_game (id, player_id, game_id, date, status, time) VALUES (default, 4, 4, '2024-08-05', 'A', '14:36:00');
INSERT INTO manager.next_game (id, player_id, game_id, date, status, time) VALUES (default, 5, 5, '2024-06-03', 'A', '10:48:00');
INSERT INTO manager.next_game (id, player_id, game_id, date, status, time) VALUES (default, 5, 5, '2024-07-22', 'A', '16:19:00');
INSERT INTO manager.next_game (id, player_id, game_id, date, status, time) VALUES (default, 5, 5, '2024-08-29', 'A', '11:07:00');
INSERT INTO manager.next_game (id, player_id, game_id, date, status, time) VALUES (default, 6, 6, '2024-05-14', 'A', '15:30:00');
INSERT INTO manager.next_game (id, player_id, game_id, date, status, time) VALUES (default, 6, 6, '2024-06-11', 'A', '12:56:00');
INSERT INTO manager.next_game (id, player_id, game_id, date, status, time) VALUES (default, 6, 6, '2024-07-03', 'A', '08:17:00');
INSERT INTO manager.next_game (id, player_id, game_id, date, status, time) VALUES (default, 7, 7, '2024-08-17', 'A', '17:43:00');
INSERT INTO manager.next_game (id, player_id, game_id, date, status, time) VALUES (default, 7, 7, '2024-05-31', 'A', '13:04:00');

INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 1, '2023-02-15', 5, 4, 7, 8, 6, 3, 9, 7, 8, 5, 8, 7, 0, 0, 1, 45, 'no comment');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 1, '2023-04-29', 8, 6, 5, 7, 9, 4, 8, 6, 7, 6, 7, 9, 1, 0, 1, 50, 'no comment');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 1, '2023-06-05', 4, 8, 9, 6, 7, 5, 6, 8, 6, 7, 8, 6, 0, 0, 1, 35, 'no comment');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 1, '2023-07-19', 9, 7, 6, 8, 5, 7, 8, 7, 9, 8, 6, 7, 0, 1, 0, 55, 'no comment');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 1, '2023-09-03', 6, 5, 7, 6, 8, 8, 7, 6, 6, 7, 6, 5, 1, 0, 0, 40, 'no comment');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 1, '2023-10-12', 7, 9, 8, 7, 6, 7, 9, 8, 6, 8, 5, 7, 0, 1, 0, 55, 'no comment');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 1, '2023-12-05', 8, 7, 6, 8, 9, 8, 7, 7, 8, 7, 8, 6, 0, 1, 0, 50, 'no comment');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 1, '2024-01-23', 4, 6, 8, 7, 8, 6, 7, 6, 8, 7, 9, 8, 0, 1, 1, 45, 'no comment');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 1, '2024-03-15', 7, 5, 9, 8, 7, 7, 6, 9, 7, 8, 5, 6, 1, 0, 1, 55, 'no comment');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 1, '2024-04-20', 5, 8, 7, 6, 8, 9, 7, 7, 9, 8, 7, 8, 0, 1, 0, 60, 'no comment');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 1, '2024-04-12', 9, 7, 6, 8, 7, 7, 9, 7, 8, 7, 8, 6, 1, 0, 0, 40, 'no comment');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 1, '2024-02-02', 6, 8, 7, 6, 7, 9, 7, 7, 9, 8, 7, 8, 0, 1, 1, 50, 'no comment');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 1, '2023-09-18', 8, 6, 7, 8, 9, 8, 7, 7, 8, 7, 8, 6, 0, 0, 0, 35, 'no comment');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 1, '2023-05-27', 6, 9, 8, 7, 6, 7, 9, 7, 6, 8, 5, 6, 0, 1, 1, 55, 'no comment');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 1, '2023-01-05', 7, 8, 7, 6, 7, 9, 8, 7, 9, 8, 7, 8, 1, 0, 0, 40, 'no comment');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 1, '2023-10-02', 5, 7, 8, 7, 6, 7, 9, 7, 6, 8, 5, 6, 0, 1, 1, 50, 'no comment');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 1, '2024-04-06', 8, 5, 6, 7, 8, 6, 7, 6, 8, 7, 9, 8, 0, 1, 0, 60, 'no comment');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 1, '2023-07-12', 4, 6, 8, 7, 8, 7, 9, 7, 8, 7, 8, 6, 0, 1, 1, 45, 'no comment');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 1, '2024-02-25', 7, 8, 7, 6, 7, 9, 8, 7, 9, 8, 7, 8, 1, 0, 0, 35, 'no comment');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 2, '2023-02-15', 7, 2, 8, 6, 4, 9, 1, 7, 2, 6, 3, 7, 0, 0, 1, 43, 'no comment');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 2, 3, 2, '2023-04-29', 9, 1, 6, 4, 8, 10, 2, 5, 9, 3, 8, 8, 1, 1, 1, 56, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 3, 3, 2, '2023-06-05', 5, 0, 5, 6, 10, 4, 1, 7, 5, 9, 8, 4, 2, 2, 0, 40, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 1, 2, '2023-02-15', 1, 2, 0, 7, 9, 10, 9, 5, 10, 3, 6, 3, 1, 1, 2, 50, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 1, 2, '2023-04-29', 6, 2, 9, 9, 6, 2, 8, 8, 6, 2, 6, 9, 0, 0, 0, 59, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 1, 2, '2023-06-05', 3, 1, 7, 9, 3, 0, 4, 3, 3, 5, 2, 10, 1, 1, 1, 47, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 1, 2, '2023-02-15', 10, 2, 4, 3, 2, 10, 5, 10, 3, 3, 9, 6, 1, 2, 0, 48, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 1, 2, '2023-04-29', 4, 0, 8, 1, 7, 7, 10, 9, 1, 6, 3, 7, 1, 0, 1, 45, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 1, 2, '2023-06-05', 8, 1, 3, 5, 5, 0, 6, 2, 4, 10, 9, 2, 0, 2, 1, 31, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 1, 2, '2023-02-15', 6, 0, 8, 10, 7, 2, 6, 3, 8, 6, 7, 9, 1, 0, 0, 59, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 1, 2, '2023-04-29', 2, 1, 6, 2, 10, 6, 4, 4, 3, 3, 5, 6, 0, 1, 1, 32, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 1, 2, '2023-06-05', 7, 2, 10, 8, 5, 4, 9, 8, 7, 4, 7, 8, 1, 0, 2, 55, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 1, 2, '2023-02-15', 4, 2, 7, 5, 9, 0, 2, 9, 5, 9, 5, 7, 0, 1, 0, 52, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 1, 2, '2023-04-29', 8, 0, 4, 4, 6, 6, 5, 5, 9, 7, 6, 10, 2, 1, 0, 57, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 2, '2023-06-05', 5, 1, 8, 9, 3, 1, 3, 10, 2, 9, 10, 8, 2, 0, 1, 44, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 2, '2023-02-15', 3, 1, 10, 6, 2, 4, 7, 4, 3, 4, 7, 7, 0, 2, 0, 37, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 2, '2023-04-29', 9, 1, 3, 5, 8, 7, 4, 8, 8, 4, 8, 6, 0, 1, 1, 39, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 2, '2023-06-05', 7, 2, 5, 2, 5, 4, 7, 1, 10, 5, 8, 9, 2, 0, 2, 55, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 3, '2023-02-15', 8, 1, 7, 4, 9, 7, 3, 10, 8, 2, 6, 7, 0, 1, 1, 50, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 3, '2023-04-29', 5, 0, 6, 5, 8, 5, 4, 7, 7, 4, 9, 7, 2, 0, 2, 45, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 3, '2023-06-05', 9, 2, 8, 3, 7, 6, 5, 8, 6, 6, 8, 6, 0, 1, 0, 38, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 3, '2023-02-15', 3, 1, 9, 6, 6, 2, 4, 8, 4, 7, 10, 6, 1, 1, 2, 57, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 3, '2023-04-29', 7, 0, 4, 9, 5, 10, 6, 9, 2, 5, 5, 8, 0, 0, 0, 52, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 3, '2023-06-05', 4, 2, 7, 7, 3, 6, 2, 8, 7, 3, 8, 9, 1, 2, 0, 58, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 3, '2023-02-15', 6, 1, 5, 8, 4, 9, 7, 3, 9, 5, 6, 7, 2, 2, 1, 32, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 3, '2023-04-29', 2, 1, 8, 2, 9, 8, 5, 6, 5, 9, 8, 8, 1, 2, 2, 51, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 3, '2023-06-05', 8, 0, 6, 6, 8, 3, 6, 7, 10, 4, 5, 10, 0, 1, 2, 35, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 3, '2023-02-15', 4, 1, 9, 4, 7, 5, 3, 9, 8, 8, 8, 7, 1, 0, 1, 43, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 1, 3, '2023-04-29', 10, 0, 7, 8, 5, 4, 7, 4, 4, 7, 7, 7, 0, 2, 1, 58, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 1, 3, '2023-06-05', 6, 1, 3, 5, 8, 7, 2, 10, 9, 6, 6, 9, 2, 1, 0, 50, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 1, 3, '2023-02-15', 3, 1, 5, 4, 10, 3, 1, 5, 4, 5, 5, 8, 2, 2, 1, 40, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 1, 3, '2023-04-29', 7, 2, 8, 7, 4, 6, 5, 8, 2, 6, 7, 10, 0, 0, 2, 36, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 1, 3, '2023-06-05', 2, 1, 4, 9, 6, 7, 9, 3, 3, 8, 6, 6, 2, 0, 1, 45, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 1, 3, '2023-02-15', 9, 0, 6, 5, 7, 5, 4, 10, 9, 3, 4, 9, 2, 1, 1, 54, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 1, 3, '2023-04-29', 5, 1, 10, 9, 4, 9, 2, 7, 7, 5, 6, 7, 1, 0, 2, 33, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 1, 3, '2023-06-05', 8, 0, 4, 2, 8, 2, 7, 8, 9, 4, 8, 8, 2, 2, 2, 47, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 4, '2023-02-15', 7, 1, 8, 6, 4, 9, 3, 10, 8, 4, 6, 8, 1, 0, 1, 42, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 4, '2023-04-29', 4, 0, 7, 5, 9, 7, 4, 8, 6, 5, 9, 7, 2, 2, 1, 55, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 4, '2023-06-05', 8, 1, 6, 3, 7, 8, 2, 9, 7, 6, 7, 9, 0, 1, 0, 36, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 4, '2023-02-15', 3, 1, 9, 7, 5, 4, 6, 8, 3, 7, 7, 7, 1, 1, 2, 51, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 4, '2023-04-29', 6, 2, 5, 8, 8, 5, 5, 7, 5, 3, 8, 6, 0, 0, 1, 46, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 4, '2023-06-05', 2, 1, 8, 9, 6, 6, 4, 8, 9, 4, 8, 9, 2, 1, 2, 58, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 4, '2023-02-15', 5, 1, 7, 5, 9, 2, 3, 9, 6, 5, 7, 7, 2, 1, 0, 57, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 4, '2023-04-29', 9, 0, 6, 2, 8, 8, 5, 6, 5, 6, 8, 8, 1, 2, 1, 33, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 4, '2023-06-05', 4, 1, 8, 6, 7, 5, 1, 9, 7, 5, 7, 8, 1, 0, 0, 41, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 4, '2023-02-15', 8, 0, 5, 4, 7, 9, 3, 10, 8, 3, 5, 7, 2, 1, 1, 48, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 4, '2023-04-29', 3, 0, 9, 6, 8, 3, 2, 8, 6, 6, 9, 6, 1, 0, 2, 47, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 4, '2023-06-05', 7, 1, 4, 8, 6, 8, 7, 9, 6, 4, 8, 10, 1, 2, 0, 39, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 4, '2023-02-15', 2, 2, 9, 6, 5, 8, 4, 7, 9, 4, 6, 8, 0, 0, 2, 54, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 4, '2023-04-29', 8, 1, 6, 3, 7, 3, 6, 8, 4, 3, 7, 9, 1, 1, 0, 38, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 4, '2023-06-05', 5, 0, 7, 8, 9, 7, 1, 10, 8, 5, 6, 8, 2, 0, 1, 59, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 4, '2023-02-15', 9, 2, 8, 5, 6, 6, 3, 8, 6, 6, 6, 7, 2, 0, 1, 49, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 4, '2023-04-29', 6, 1, 4, 7, 7, 9, 4, 5, 7, 6, 6, 10, 2, 0, 2, 42, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 4, '2023-06-05', 3, 0, 9, 6, 8, 2, 2, 8, 9, 3, 7, 6, 0, 1, 1, 44, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 5, '2023-02-15', 6, 2, 8, 4, 7, 9, 2, 6, 6, 3, 8, 7, 0, 1, 0, 47, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 5, '2023-04-29', 3, 1, 5, 8, 9, 5, 5, 9, 8, 5, 9, 8, 1, 0, 2, 56, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 5, '2023-06-05', 9, 0, 7, 7, 6, 6, 4, 10, 6, 4, 6, 9, 2, 2, 1, 59, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 5, '2023-02-15', 5, 1, 6, 3, 8, 8, 3, 9, 7, 5, 6, 10, 1, 1, 1, 39, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 5, '2023-04-29', 8, 2, 9, 7, 4, 6, 2, 7, 8, 4, 7, 7, 2, 0, 0, 50, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 5, '2023-06-05', 2, 1, 7, 6, 9, 7, 5, 8, 5, 5, 9, 8, 2, 2, 1, 43, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 5, '2023-02-15', 7, 1, 8, 5, 6, 4, 3, 8, 6, 6, 6, 9, 1, 1, 0, 57, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 2, 5, '2023-04-29', 4, 0, 9, 8, 5, 10, 6, 9, 6, 4, 8, 7, 2, 2, 2, 34, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 5, '2023-06-05', 9, 1, 5, 4, 7, 7, 4, 8, 9, 5, 7, 7, 0, 1, 1, 58, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 5, '2023-02-15', 4, 1, 6, 8, 8, 3, 4, 9, 7, 6, 8, 8, 1, 0, 0, 45, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 5, '2023-04-29', 7, 0, 8, 6, 7, 8, 6, 6, 5, 5, 7, 9, 1, 1, 1, 53, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 5, '2023-06-05', 2, 1, 7, 5, 9, 6, 5, 7, 8, 4, 7, 6, 2, 2, 2, 52, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 5, '2023-02-15', 8, 2, 5, 6, 7, 8, 2, 5, 6, 6, 8, 7, 1, 0, 1, 41, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 5, '2023-04-29', 3, 1, 8, 7, 6, 4, 6, 8, 7, 5, 6, 8, 0, 0, 0, 30, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 5, '2023-06-05', 8, 0, 4, 5, 7, 9, 4, 7, 6, 5, 6, 8, 2, 1, 1, 44, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 5, '2023-02-15', 6, 1, 9, 8, 5, 7, 3, 10, 8, 4, 7, 9, 0, 1, 2, 55, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 5, '2023-04-29', 2, 1, 6, 7, 8, 6, 4, 9, 8, 6, 7, 7, 2, 0, 1, 59, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 5, '2023-06-05', 7, 0, 8, 9, 6, 3, 5, 9, 6, 6, 8, 8, 1, 2, 2, 36, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 5, '2023-02-15', 4, 1, 7, 4, 6, 7, 2, 8, 7, 5, 5, 8, 2, 1, 1, 58, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 1, 3, 5, '2023-06-05', 7, 3, 8, 6, 9, 7, 4, 8, 7, 5, 7, 8, 2, 1, 0, 57, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 2, 3, 6, '2023-02-15', 6, 2, 8, 4, 7, 9, 2, 6, 6, 3, 8, 7, 0, 1, 0, 47, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 2, 3, 6, '2023-04-29', 3, 1, 5, 8, 9, 5, 5, 9, 8, 5, 9, 8, 1, 0, 2, 56, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 2, 3, 6, '2023-06-05', 9, 0, 7, 7, 6, 6, 4, 10, 6, 4, 6, 9, 2, 2, 1, 59, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 2, 3, 6, '2023-02-15', 5, 1, 6, 3, 8, 8, 3, 9, 7, 5, 6, 10, 1, 1, 1, 39, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 2, 3, 6, '2023-04-29', 8, 2, 9, 7, 4, 6, 2, 7, 8, 4, 7, 7, 2, 0, 0, 50, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 3, 3, 7, '2023-02-15', 6, 2, 8, 4, 7, 9, 2, 6, 6, 3, 8, 7, 0, 1, 0, 47, 'good game');
INSERT INTO manager.player_observation (id, game_id, user_id, player_id, date, marking, set_pieces, technique, heading, passing, agression, decisions, teamwork, acceleration, pace, stamina, strenght, goals, assists, cards, minutes, comment) VALUES (default, 3, 3, 7, '2023-04-29', 3, 1, 5, 8, 9, 5, 5, 9, 8, 5, 9, 8, 1, 0, 2, 56, 'good game');

INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 1, 5);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 2, 9);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 3, 3);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 4, 11);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 5, 8);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 6, 2);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 7, 7);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 8, 4);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 9, 10);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 10, 6);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 11, 1);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 12, 5);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 13, 9);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 14, 3);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 15, 11);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 16, 8);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 17, 2);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 18, 7);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 19, 4);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 20, 10);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 21, 5);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 22, 9);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 23, 3);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 24, 11);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 25, 8);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 26, 2);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 27, 7);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 28, 4);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 29, 10);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 30, 6);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 31, 1);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 32, 5);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 33, 9);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 34, 3);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 35, 11);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 36, 8);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 37, 2);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 38, 7);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 39, 4);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 40, 10);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 41, 5);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 42, 9);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 43, 3);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 44, 11);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 45, 8);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 46, 2);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 47, 7);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 48, 4);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 49, 10);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 50, 6);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 51, 1);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 52, 5);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 53, 9);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 54, 3);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 55, 11);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 56, 8);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 57, 2);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 58, 7);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 59, 4);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 60, 10);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 61, 5);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 62, 9);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 63, 3);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 64, 11);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 65, 8);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 66, 2);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 67, 7);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 68, 4);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 69, 10);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 70, 6);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 71, 1);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 72, 5);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 73, 9);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 74, 3);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 75, 11);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 76, 8);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 77, 2);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 78, 7);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 79, 4);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 80, 10);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 81, 5);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 82, 9);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 83, 3);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 84, 11);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 85, 8);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 86, 2);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 87, 7);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 88, 4);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 89, 10);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 90, 6);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 91, 1);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 92, 5);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 93, 9);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 94, 3);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 95, 11);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 96, 8);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 97, 2);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 98, 7);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 99, 4);
INSERT INTO manager.observation_position (id, player_observation_id, position_id) VALUES (default, 100, 10);















